config/routes.rb
CalendarReminders::Application.routes.draw do
  delete "contacts/destroy_selected"
  resources :contacts

  resources :appointments do
    member do
      post 'send_reminder'
    end
  end

  resources :profile, only: [:index]

  resources :reminders, only: [:create]

  resources :settings, only: [:index, :update]

  get "authentication/index"

  get "info/about"
  get "info/contact"
  get "info/legal"
  get "info/beta_notice"

  get "home/index"

  get "sessions/new"
  get "sessions/authorize"
  delete "sessions/destroy"

  root 'home#index'
end

app/models/contact.rb
class Contact < ActiveRecord::Base
  belongs_to :user
  has_many :appointment, dependent: :destroy

  scope :undeleted, -> { where(deleted: false) }

  def delete
    self.update_attributes(:deleted => true)

    Appointment.where(contact_id: self.id).each { |appt| appt.delete }
  end
end

app/models/google/contact.rb
class Contact

  cattr_accessor :service

  class << self

    @@service = nil
    
    def find_all
      @@service.get_all_contacts
    end

  end

end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :authorize
  before_action :set_contact, only: [:show, :edit, :update, :destroy]

  # GET /contacts
  # GET /contacts.json
  def index
    @contacts = Contact.undeleted.where(user_id: current_user.id)
  end

  # GET /contacts/1
  # GET /contacts/1.json
  def show
  end

  # GET /contacts/new
  def new
    @contact = Contact.new
  end

  # GET /contacts/1/edit
  def edit
  end

  # POST /contacts
  # POST /contacts.json
  def create
    @contact = Contact.new(contact_params.merge(user_id: current_user.id))

    respond_to do |format|
      if @contact.save
        format.html { redirect_to contacts_url, notice: 'Contact was successfully created.' }
        format.json { render action: 'show', status: :created, location: @contact }
      else
        format.html { render action: 'new' }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contacts/1
  # PATCH/PUT /contacts/1.json
  def update
    respond_to do |format|
      if @contact.update(contact_params.merge(user_id: current_user.id))
        format.html { redirect_to contacts_url, notice: 'Contact was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1
  # DELETE /contacts/1.json
  def destroy
    @contact.delete
    respond_to do |format|
      format.html { redirect_to contacts_url }
      format.json { head :no_content }
    end
  end

  def destroy_selected
    selected_contacts.each do |id|
      contact = Contact.find(id)
      contact.delete
    end

    flash[:success] = "Contact(s) deleted" unless selected_contacts.empty?
    redirect_to contacts_url
  end

  private

  def selected_contacts
    contacts = []
    params.each_key do |key|
      if (key =~ /selected_contact_id_(\d+)/)
        contacts << $1
      end
    end

    return contacts
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_contact
    @contact = Contact.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def contact_params
    params.require(:contact).permit(:name, :phone_number)
  end
end

app/views/contacts/_contacts_grid.html.erb
<%= form_tag({controller: "contacts", action: "destroy_selected"}, method: "delete") do %>
  <%= submit_tag 'Delete', class: "btn btn-danger", 
    data: { confirm: "Are you sure you wish to delete the selected contact(s)?\n"\
      "Any appointments associated with the contact(s) will also be deleted."} %>
  <table class="table table-striped table-bordered">
    <thead>
      <tr>
        <th>Select</th>
        <th>Name</th>
        <th>Phone number</th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @contacts.each do |contact| %>
        <tr>
          <td><%= check_box_tag("selected_contact_id_#{contact.id}") %></td>
          <td><%= contact.name %></td>
          <td><%= contact.phone_number %></td>
          <td><%= link_to 'Edit', edit_contact_path(contact), class: "btn btn-default" %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>

app/views/contacts/_form.html.erb
<%= form_for(@contact) do |f| %>
  <% if @contact.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@contact.errors.count, "error") %> prohibited this contact from being saved:</h2>

      <ul>
      <% @contact.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :phone_number %><br>
    <%= f.text_field :phone_number %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/contacts/edit.html.erb
<h1>Edit contact</h1>

<%= render 'form' %>

app/views/contacts/index.html.erb
<h1>Contacts</h1>
<%= link_to 'New Contact', new_contact_path, class: "pull-right btn btn-default" %>
<% if @contacts.count > 0 %>
  <%= render "contacts_grid" %>
<% else %>
  <i>No contacts found</i>
<% end %>

app/views/contacts/new.html.erb
<h1>New contact</h1>

<%= render 'form' %>