config/routes.rb
CalendarReminders::Application.routes.draw do
  delete "contacts/destroy_selected"
  resources :contacts

  resources :appointments do
    member do
      post 'send_reminder'
    end
  end

  resources :profile, only: [:index]

  resources :reminders, only: [:create]

  resources :settings, only: [:index, :update]

  get "authentication/index"

  get "info/about"
  get "info/contact"
  get "info/legal"
  get "info/beta_notice"

  get "home/index"

  get "sessions/new"
  get "sessions/authorize"
  delete "sessions/destroy"

  root 'home#index'
end

app/models/appointment.rb
require_relative '../services/twilio_api'

class Appointment < ActiveRecord::Base

  belongs_to :user
  belongs_to :contact

  has_many :reminder_history_entries, dependent: :destroy
  has_many :settings, through: :user

  validates_presence_of :user, :contact, :start, :end

  scope :upcoming, -> { where("start > ?", Time.now) }
  scope :past, -> { where("start < ?", Time.now) }

  scope :undeleted, -> { where(deleted: false) }
  scope :deleted, -> { where(deleted: true) }

  def delete
    self.update_attributes(:deleted => true)
  end

  def send_reminder
    if self.reminder_sent?
      raise StandardError.new "Cannot send reminder. A reminder was already sent for this appointment."
    elsif self.user.reminders_sent_in_current_month >= GlobalSetting::MAX_MONTHLY_REMINDERS_PER_USER
      raise StandardError.new "Cannot send reminder. User has reached their monthly reminder limit"
    end

    phone_number_setting = user.settings.where(key: Setting::KEYS[:phone_number]).first
    callback_number = phone_number_setting.value unless phone_number_setting.nil?

    message_text = "#{contact.name}, this is a reminder for your appt with #{user.name} "\
      "@ #{start.localtime.strftime('%l:%M %p %-m/%e/%y')}. "\
      "Call #{callback_number.blank? ? 'them' : callback_number} if you can't keep it."

    phone_number = contact.phone_number

    twilio_api_client.send_sms_message(phone_number, message_text)

    reminder_history_entries.create
  end

  def reminder_sent?
    reminder_history_entries.count > 0
  end

  class << self
    def unreminded_upcoming
      unreminded = find_by_sql(
        "SELECT * FROM ( "\
          "SELECT appointments.*, count(reminder_history_entries.id) AS reminder_count "\
          "FROM appointments "\
          "LEFT OUTER JOIN reminder_history_entries "\
            "ON appointments.id = reminder_history_entries.appointment_id "\
          "WHERE appointments.deleted = false "\
          "GROUP BY appointments.id "\
        ") AS apt_reminders "\
        "WHERE reminder_count = 0 AND apt_reminders.start > UTC_TIMESTAMP();")

      user_reminder_advance_times = {}
      unreminded.select do |apt|
        unless user_reminder_advance_times[apt.user_id]
          user_reminder_advance_times[apt.user_id] = 
            apt.settings.where(key: Setting::KEYS[:reminder_advance_time]).first.base_units_normalized_value
        end

        # time addition is in seconds, the normalized reminder advance time is in minutes
        apt.start < (Time.now.utc + user_reminder_advance_times[apt.user_id] * 60)
      end
    end
  end

  private

  def twilio_api_client
    @@client ||= TwilioApi.new
  end
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController

  before_filter :authorize

  def index
    appt_filter = params[:filter] || :upcoming

    case appt_filter.to_sym
      when :upcoming
        @appointments = Appointment.where(user_id: current_user.id).undeleted.upcoming
      when :past
        @appointments = Appointment.where(user_id: current_user.id).undeleted.past
      when :all
        @appointments = Appointment.where(user_id: current_user.id).undeleted
      else
        raise StandardError.new "Unknown appointment filter type #{appt_filter}"
    end 
  end

  def new
    @contacts = Contact.undeleted.where(user_id: current_user.id)
  end

  def create
    apt_params = parse_appointment_params
    apt_params.merge!(user_id: current_user.id)
    appointment = Appointment.create(apt_params)

    if (appointment.persisted?)
      flash[:success] = "Appointment saved successfully"
      redirect_to appointments_path
    else
      flash.now[:error] = "There was a problem saving your appointment:\n #{appointment.errors.full_messages}"
      render :new
    end
  end

  def update
    apt = Appointment.find(params[:id].to_i)

    apt_params = parse_appointment_params
    apt_params.merge!(user_id: current_user.id)

    apt.update(apt_params)

    if (apt.persisted?)
      flash[:success] = "Appointment saved successfully"
      redirect_to appointments_path
    else
      flash.now[:error] = "There was a problem saving your appointment"
      render :edit
    end
  end

  def edit
    @appointment = Appointment.find(params[:id].to_i)
    @contacts = Contact.undeleted.where(user_id: current_user.id)
  end

  def destroy
    apt = Appointment.find(params[:id])

    if (apt.delete)
      flash[:success] = "Appointment deleted successfully"
    else
      flash[:error] = "Appointment was not deleted succesfully"
    end

    redirect_to appointments_path
  end

  private

  def parse_appointment_params
    start_str = "#{params[:start_date]} #{params[:start_time]}"
    
    begin
      apt_start = Time.parse(start_str)
      apt_end = apt_start + (params[:duration].to_i * 60)
      contact_id = params[:appointment][:contact_id] if params[:appointment]

      return { start: apt_start, end: apt_end, contact_id: contact_id }
    rescue
      return {}
    end
  end
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
  def now_rounded_to_next_hour
    hour_from_now = Time.now + 1.hour

    return Time.new(
      hour_from_now.year,
      hour_from_now.month,
      hour_from_now.day,
      hour_from_now.hour,
      0,
      0)
  end
end

app/views/appointments/_appointments_grid.html.erb
<table class="table table-striped table-bordered">
  <thead>
    <tr>
      <th>Start</th>
      <th>Duration</th>
      <th>Client</th>
      <th>Reminder sent</th>
      <th colspan="2">Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @appointments.each do |apt| %>
      <tr>
        <td><%= apt.start.localtime.strftime('%A %B %e %Y, %l:%M %p') %></td>
        <td><%= "#{((apt.end.localtime - apt.start.localtime) / 60).to_i} minutes" %></td>
        <td><%= apt.contact.name %></td>
        <td>
          <div class="text-center">
            <% if apt.reminder_sent? %>
              <span class="glyphicon glyphicon-ok" />
            <% else %>
              <span class="glyphicon glyphicon-minus" />
            <% end %>
          </div>
        </td>
        <td><%= link_to "Edit", edit_appointment_path(apt.id), :method => :get, class: "btn btn-default" %></td>
        <td><%= button_to "Delete", appointment_path(apt.id), :method => :delete, 
          confirm: "Are you sure you wish to delete this appointment?", 
          class: "btn btn-danger" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/appointments/_edit_form.html.erb
<% @now = now_rounded_to_next_hour %>
<span>Start:</span>
<input type="time" name="start_time" step="900" value="<%= @appointment ? 
  @appointment.start.to_time.localtime.strftime("%H:%M") : @now.strftime("%H:%M") %>"/>
<input type="date" name="start_date" value="<%= @appointment ? @appointment.start.localtime.to_date : @now.to_date.to_s %>"/>
<br/>
<span>Duration:</span>
<input type="number" name="duration" step="15" min="0" max="90" 
  value="<%= @appointment ? ((@appointment.end.to_time - @appointment.start.to_time) / 60).to_i : 60 %>" />
<span>minutes</span>
<p>
  <span>Contact:</span>
  <% if !@contacts.blank? %>
    <%= select(:appointment, :contact_id, @contacts.collect { |c| [c.name, c.id] }) %>
  <% else %>
    <i>No contacts found. Add some to create an appointment.</i>
  <% end %>
</p>
<br/>

app/views/appointments/edit.html.erb
<h1>Edit appointment</h1>
<%= form_tag({controller: "appointments", action: "update"}, method: "patch") %>
  <%= render "edit_form" %>
  <input type="submit" value="Save appointment" />
</form>

app/views/appointments/index.html.erb
<h1>Appointments</h1>
<%= link_to "New Appointment", new_appointment_path, { class: "btn btn-default pull-right" } %>
<form>
  <label for="filter">Filter:</label>
  <%= select_tag(:filter, options_for_select([:upcoming, :past, :all], params[:filter].nil? ? :upcoming : params[:filter]), 
    { onchange: "this.form.submit()" })%>
</form>
<% if @appointments.count > 0 %>
  <%= render "appointments_grid" %>
<% else %>
  <i>No appointments found</i>
<% end %>

app/views/appointments/new.html.erb
<h1>New appointment</h1>
<%= form_tag({controller: "appointments", action: "create"}, method: "post") %>
  <%= render "edit_form" %>
  <input type="submit" value="Create appointment" />
</form>