config/routes.rb
CalendarReminders::Application.routes.draw do
  delete "contacts/destroy_selected"
  resources :contacts

  resources :appointments do
    member do
      post 'send_reminder'
    end
  end

  resources :profile, only: [:index]

  resources :reminders, only: [:create]

  resources :settings, only: [:index, :update]

  get "authentication/index"

  get "info/about"
  get "info/contact"
  get "info/legal"
  get "info/beta_notice"

  get "home/index"

  get "sessions/new"
  get "sessions/authorize"
  delete "sessions/destroy"

  root 'home#index'
end

app/views/layouts/_auth.html.erb
<div id="myModal" class="modal fade">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title">Sign in or register</h4>
      </div>
      <div class="modal-body">
        <p>Use your existing Google account to sign in or register. Click the "Sign in with Google" button to proceed.
          If you don't have an account, <%= link_to "click here", "https://accounts.google.com/SignUp" %> to create one.</p>
        <%= link_to image_tag('google/Red-signin-Long-base-44dp.png', size: "200x40"), sessions_new_path %>
        <br/>
        <br/>
        <br/>
        <small>By logging in to the application, you are indicating that you have read and agree to
          our <%= link_to "legal notice", "#{root_url}info/legal" %>.</small>
      </div>
      <div class="modal-footer">
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->
<script>
</script>

app/views/layouts/_footer.html.erb
<footer>
  <div id="footer-functions" class="navbar-fixed-bottom">
    <div class="navbar navbar-default">
      <div class="container">
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to "Company", "#{root_url}info/about" %></li>
          <li><%= link_to "Contact", "#{root_url}info/contact" %></li>
          <li><%= link_to "Legal", "#{root_url}info/legal" %></li>
        </ul>
        <small class="navbar-text navbar-left">
          Calendar Reminders v <%= ::APPLICATION_VERSION %> |
          &copy; 2013 - <%= Time.now.year %> Jonathan Worek
        </small>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header>
  <nav id="top-navigation-bar" class="navbar navbar-default navbar-fixed-top" role="navigation">
    <div class="container">
      <div id="brand" class="navbar-brand">
        <span class="glyphicon glyphicon-calendar">
      </div>
      <% if current_user %>
        <div class="navbar-left" >
          <ul class="nav navbar-nav">
            <li><%= link_to "Appointments", "#{root_url}appointments" %></li>
            <li><%= link_to "Contacts", "#{root_url}contacts" %></li>
          </ul>
        </div>
      <% else %>
        <a href="<%= root_url %>" class="navbar-brand">Calendar Reminders</a>
      <% end %>
      <div id="auth" class="navbar-right">
        <ul class="nav navbar-nav">
          <% if current_user %>
            <li><%= link_to "Settings", "#{root_url}settings" %></li> 
            <li><%= link_to "Profile", "#{root_url}profile" %></li> 
            <li><%= link_to "Sign out", sessions_destroy_path, { method: 'delete' } %></li>
          <% else %>
            <li><%= link_to("Sign in/Register", "#", { "data-toggle" => "modal", "data-target" => "#myModal" }) %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Calendar Reminders</title>
  <link href="//netdna.bootstrapcdn.com/bootstrap/3.0.3/css/bootstrap.min.css" rel="stylesheet">
  <script src="http://code.jquery.com/jquery-1.10.1.min.js"></script>
  <script src="//netdna.bootstrapcdn.com/bootstrap/3.0.3/js/bootstrap.min.js"></script>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<%= render 'layouts/header' 
%>
<body class="container">
  <% if !flash.empty? %>
    <% if flash[:success] %>
      <div id="messages_success" class="alert alert-success">
        <p><%= flash[:success] %></p>
      </div>
    <% end %>
    <% if flash[:error] %>
      <div id="messages_failure" class="alert alert-danger">
        <p><%= flash[:error] %></p>
      </div>
    <% end %>
  <% end %>
  <div id="content" class="col-md-12">
    <!-- Here goes the individual page content -->
    <%= render 'layouts/auth' %>
    <%= yield %>
  </div>
  <%= render 'layouts/footer' %>
</body>
</html>